version: 0.0
os: linux
files:
  - source: /*.js
    destination: /home/ec2-user/express-service
  - source: /public/**/*
    destination: /home/ec2-user/express-service/public
  - source: /views/**/*
    destination: /home/ec2-user/express-service/views
  - source: /scripts/*
    destination: /home/ec2-user/express-service/scripts
  - source: /package.json
    destination: /home/ec2-user/express-service
  - source: /node_modules
    destination: /home/ec2-user/express-service/node_modules
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/codestar_remote_access
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
